Closes #31: Add a check if page is scrolled down.
wp-media/rocket-scripts pull request #32
Opened 2024-10-08 02:12 UTC by Miraeld

# Description

Fixes #31 
This PR adds a check to ensure that the beacon is not fired if the page is scrolled down before it runs. 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue).

## Detailed scenario

- Use - https://gist.github.com/DahmaniAdame/bd58d4be051f5995aa2318d341eb342a
- Scroll to the last image
- Hit refresh while making sure the beacon runs
- See the LCP image will be related to the current viewport

## Technical description

### Documentation

The `_isPageScrolled()` method is used in `BeaconManager.js` to check if the page is scrolled and bails out if it returns true. In-build test have been added as well.

### New dependencies

None

### Risks

None

# Mandatory Checklist

## Code validation

- [x] I validated all the Acceptance Criteria. If possible, provide screenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I protected entry points against unexpected inputs.
- [x] I did not introduce unnecessary complexity.
- [x] Output messages (errors, notices, logs) are explicit enough for users to understand the issue and are actionnable.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.
- [x] When possible, I prepared ways to observe the implemented system (logs, data, etc.).
- [x] I added error handling logic when using functions that could throw errors (HTTP/API request, filesystem, etc.)

2024-10-08 09:02 UTC, Khadreal submitted a review, later dismissed

2024-10-14 08:21 UTC, wordpressfan requested changes
I think @Miraeld is not working today, I'll go ahead and do that small change by myself.

2024-10-14 08:21 UTC, wordpressfan commented on src/BeaconManager.js
> +    }
This should be an `Util` method so it can be used anywhere

2024-10-15 15:41 UTC, Khadreal approved these changes

2024-10-16 06:15 UTC, wordpressfan approved these changes

2024-10-16 08:06 UTC, merged