adjust beacon timeout using delay value wp-media/wp-rocket--#6741
wp-media/rocket-scripts pull request #5
Opened 2024-07-29 08:21 UTC by Khadreal

# Description
Adjust timeout, make the value dynamic

Fixes #6741

## Documentation

### User documentation

Adjust the timeout to use the filter value from the backend.

### Technical documentation

*Explain how this code works. Diagram & drawings are welcomed.*

## Type of change
- [x] Enhancement (non-breaking change which improves an existing functionality).

## New dependencies
*List any new dependencies that are required for this change.*

## Risks
*List possible performance & security issues or risks, and explain how they have been mitigated.*

# Checklists

## Feature validation

- [ ] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [ ] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [ ] I implemented built-in tests to cover the new/changed code.

## Documentation

- [ ] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [ ] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [ ] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

## Code style
- [x] I wrote self-explanatory code about what it does.
- [ ] I wrote comments to explain why it does it.
- [x] I named variables and functions explicitely.
- [ ] I protected entry points against unexpected inputs.
- [x] I did not introduce unecessary complexity.
- [ ] I listed the introduced external dependencies explicitely on the PR.
- [ ] I validated the repo-specific guidelines from CONTRIBUTING.md.

2024-07-29 12:15 UTC, Miraeld approved these changes, later dismissed

2024-07-31 13:25 UTC, Tabrisrp approved these changes, later dismissed

2024-08-01 15:32 UTC, MathieuLamiot commented
@Khadreal There are conflicts to solve it seems, this branch should be updated against the trunk I guess.

Here are steps to be able to test the script with WP Rocket: https://wp-media.slack.com/archives/CUT7FLHF1/p1722526242449019?thread_ts=1722509646.276189&cid=CUT7FLHF1

2024-08-01 16:45 UTC, MathieuLamiot requested changes
It seems that the expected behavior is not clear based on the discussion you are having. The expected behavior is:
if the init method runs for more than 10 seconds, then the script status result is failed.

The sequence is as follows:
script starts and creates a new BeaconManager.
On DOMContentLoaded , the script waits for rocket_beacon_data.delay
After the delay, init() is called. 

The issue originally was that the timer was starting at point 1. Hence, the timer was running during the delay. This is something we don't want, hence the GH issue.

So, to solve this, the only thing we need is to do 
`this.scriptTimer = /* @__PURE__ */ new Date();`
at the beginning of init() instead of when instanciating `BeaconManager`

Therefore, we are sure the timer only runs during init() and the delay is not impacting it, regardless of its value.

2024-08-01 16:45 UTC, MathieuLamiot commented on dist/wpr-beacon.js
> +      if (delay <= scriptTime) {
Change to remove.

2024-08-01 16:48 UTC, MathieuLamiot commented
@DahmaniAdame to confirm my latest comment. But I think the original issue jumped directly into a solution (doing delay + 10) which caused the confusion, since there is a better way to handle this.

2024-08-02 11:24 UTC, MathieuLamiot approved these changes

2024-08-02 11:25 UTC, MathieuLamiot commented
Changed base branch to develop. see https://wp-media.slack.com/archives/CUT7FLHF1/p1722593397186219?thread_ts=1722509646.276189&cid=CUT7FLHF1

2024-08-06 07:42 UTC, hanna-meda approved these changes
This PR looks good. Tested with steps from [TC](https://wpmediaqa.testrail.io/index.php?/cases/view/16423&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=5875). 
Thank you.

2024-08-07 09:23 UTC, merged